spring.application.name=EcommercePlatform

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=Tarun@123
spring.jpa.hibernate.ddl-auto=update

# JPA Properties
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Connection pool settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# Stripe Configuration (from environment variables)
stripe.api.secret-key=${STRIPE_SECRET_KEY}
stripe.api.public-key=${STRIPE_PUBLIC_KEY}

# Logging
logging.level.com.ecommerce.ecommerceplatform=DEBUG
spring.web.cors.allowed-origins=http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
